default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: jobjogger_api_development
  username: <%= ENV.fetch("JOBJOGGER_API_DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("JOBJOGGER_API_DATABASE_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("JOBJOGGER_API_DATABASE_HOST") { "localhost" } %>

test:
  <<: *default
  database: jobjogger_api_test

production:
  primary: &primary_production
    <<: *default
    database: jobjogger_api_production
    username: jobjogger_api
    password: <%= ENV["JOBJOGGER_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: jobjogger_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: jobjogger_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: jobjogger_api_production_cable
    migrations_paths: db/cable_migrate
